# KERNEL
DEBUG_FLAG = '-d'
SLEEP_TIME_BETWEEN_PROCESSOS = 3

# MEMORIA
REAL_TIME_START_INDEX = 0
USUARIOS_START_INDEX = 64
USUARIOS_SIZE_LIMIT = 960
REAL_TIME_SIZE_LIMIT = 64

MEMORY_REAl_TIME_SIZE = 64
MEMORY_USER_SIZE = 960

TAMANHO_MAXIMO_TOTAL_DA_FILA = 1000


MAX_PRIORIDADE_FILA1 = 20
MAX_PRIORIDADE_FILA2 = 21
MAX_PRIORIDADE_FILA3 = 50
QUANTUM_FILA1 = 5
QUANTUM_FILA2 = 10
QUANTUM_FILA3 = 15
TEMPO_ESPERA_ENVELHECIMENTO = 5
