# KERNEL
DEBUG_FLAG = '-d'
SLEEP_TIME_BETWEEN_PROCESSOS = 3

# MEMORIA
REAL_TIME_START_INDEX = 0
USUARIOS_START_INDEX = 64
USUARIOS_SIZE_LIMIT = 960
REAL_TIME_SIZE_LIMIT = 64

MEMORY_REAl_TIME_SIZE = 64
MEMORY_USER_SIZE = 960
